### ISSUE TITLE
problem with players

### ISSUE THREAD

**Issue by shannonhoon** [Blodjer/HueImmersive#16]
hi,first my english is very poor,i'll try anyway
i have the hue starter kit with the new bridge an hueimmersive instaled,all conected and work fine with my desk,the problem is when i play a movie with any player,i go to fullscreen,and the lights turn on violet and dont make anything....i used to use wmpclassic,but the same with VLC or WMP,the curious thing is that when i play a video on youtube on a fullscreen,i get the ambilight effect prefectly
sorry by my english and i hope blodjer or anyone can help me thanks

**Comment by Blodjer** [comment]
Hi shannonhoon,
I'm sorry for your experience. For me VLC and WMP work great with HueImmersive.
HueImmersive can't capture true-fullscreen applications like games. YouTube just increases the size of the video and put it in front to overlay the Windows Taskbar. For my knowledge VLC and WMP do the same, so that shouldn't be a problem.
Maybe you can change some settings inside your movie player.

**Comment by shannonhoon** [comment]
thanks blodjer,i think that xp is the possible cause,i have two pcs,both with xp and same problem,then  i installed windows 7 in secumndary pc and woek perfectly,but turn on my computer very slow,then back to xp and same problem again,finally i can solved at least temporally,installing xbmc and playing the movies across to....working now in this way,sadly i have to use hueimmersive+xbmc to have it
