### ISSUE TITLE
Gaming problems

### ISSUE THREAD

**Issue by MirkoHuf** [Blodjer/HueImmersive#4]
Hello Jannik,

thanks for your great tool - I really love it. But I have a problem when I start any type of games. The lights don't change the colors during the game. If I switch to the desktop and back to the game (with ALT+TAP) the lights changed the color to the right game screen color - but only for a single time. After that - it's static. Any hint what I can try?

**Comment by Rauks** [comment]
Hello,

I encountered the same kind of behavior. It's linked to the fact that in full screen gaming the rendering is handeled by DirectX (or an equivalent), and not by the Windows' windows manager. 
You can have the colors following the screen by setting the game to be in windowed fullscreen. But be aware that can reduce the in game performance and will disable the SLI or Crossfire if you have any.

Hoping that can help :)

Regards.

**Comment by MirkoHuf** [comment]
Hi,

thanks for the quick response. I think there is no other solution? I don't
have SLI, but I think GTA5 need more power than the Windows window manager
can provide :-)

2015-09-02 15:59 GMT+02:00 Karl Woditsch <notifications@github.com>:

**Comment by Blodjer** [comment]
Thanks @Rauks for the answer. You're almost right, the problem is the fullscreen mode (not directx).

As you might have noticed the app is currently not in development. So the best solution is to set the game in windowed fullscreen (sometimes called frameless window). I have no performance issues with this mode. For me, it even runs better.
If you have a game which not support windowed fullscreen you can use a program like [Borderless-Gaming](https://github.com/Codeusa/Borderless-Gaming/releases/latest). It sets your window in a frameless window.

Regards,
Jannik

**Comment by MirkoHuf** [comment]
Thanks - works great with GTA 5 and frameless window mode :-)
